name: Unit Tests
on:
  pull_request:
    branches:
      - "*"
jobs:
  start_runner:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: authorize
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Run ECS Task with Runner
        id: run-ecs-task-runner
        uses: geekcell/github-action-aws-ecs-run-task@v3.0.0
        with:
          cluster: Github-Actions-Cluster
          task-definition: GitHub-Actions-Runner-Task
          subnet-ids: |
            subnet-0345564be17a91f7a
            subnet-0936b44dd7729cb7d
          security-group-ids: sg-055300fefe3332569
          tail-logs: true
          assign-public-ip: 'ENABLED'
          override-container: github-runner
          #we can override the ecs container environment variables if needed
          override-container-environment: |
            GITHUB_ACCESS_TOKEN=${{ secrets.GH_TOKEN }}
            RUNNER_NAME=runner-for-unit-tests
            RUNNER_REPOSITORY_URL=https://github.com/${{ github.repository }}
  unit_tests:
    runs-on: runner-for-unit-tests
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: authorize
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Run ECS Task
        id: run-ecs-task-unit-tests
        uses: geekcell/github-action-aws-ecs-run-task@v3.0.0
        with:
          cluster: Github-Actions-Cluster
          task-definition: unit-test
          subnet-ids: |
            subnet-0345564be17a91f7a
            subnet-0936b44dd7729cb7d
          security-group-ids: sg-055300fefe3332569
          tail-logs: true
          assign-public-ip: 'ENABLED'
          override-container: aws-ecs-test
          override-container-environment: |
            GIT_BRANCH=${{ github.head_ref || github.ref_name }}
